### ISSUE TITLE
Add the ability to import data packages to pytak.

### ISSUE THREAD

**Issue by ampledata** [ampledata/pytak#13]
Since most TAK clients (ATAK, WinTAK, TAK Tracker, et al) support .pref/data-packages for server configuration, add this capability to PyTAK as well.

**Comment by thesle3p** [comment]
being able to export data packages to a server would also be useful for sensors that gather data not suitable for COT

**Comment by berkay-karlik** [comment]
is this related to uploading data packages to the server or is it just between clients? I'm looking for a way to send data-packages to official tak server using python. This repos is great for sending cot but couldn't figured how to send images (via data-packages or any other way).
