### ISSUE TITLE
Receiving COT from TAK server

### ISSUE THREAD

**Issue by zemskymax** [ampledata/pytak#14]
They is a great project! Thank you for sharing.
Have you ever managed to read CoT out of the TAK Server?
I am trying to create a simple client application that sends telemetry info (e.g., GPS) and receivs markers/routs as a Cursor on Target (COT) to and from the Free TAK Server.

Thank you

**Comment by ampledata** [comment]
I've implemented the Class for this in `EventReceiver`, but there's no protocol factories for it yet (that is, you could build a queue worker for it, but you'd still need to implement the TCP socket receiver/server, etc).

In the interim there's a couple of options:

1) If you want to receive COT and process it, use Node-RED: https://nodered.org/

2) If you want to receive COT and route it, use @tkuester's taky: https://github.com/tkuester/taky

Happy to connect directly if you'd like to discuss further: gba@undef.net
